name: CI
# Triggers the workflow on push / pull request events / manual trigger
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.10.4

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=50%

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v5.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          flags: ${{ matrix.os }}

      - name: Build
        run: yarn build
